Hooks: Make them more verbose
Communicate what we're doing and what goes wrong. Also, standardize on
bash with stricter settings.

diff --git a/hooks/post-up/04-airport b/hooks/post-up/04-airport
--- a/hooks/post-up/04-airport
+++ b/hooks/post-up/04-airport
@@ -1,9 +1,22 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# When the "airport" utility exists, symlink it to our local bin. We'd like to
-# do this only for the "home" tag, but rcm doesn't support per-tag hooks.
-airport_src="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
-airport_dst="${HOME}/.local/bin/airport"
-if [ -e "$airport_src" ] && ! [ -e "$airport_dst" ]; then
-  ln -s "$airport_src" "$airport_dst"
-fi
+set -euo pipefail
+
+link_airport_cmd() {
+  airport_src="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
+  airport_dst="${HOME}/.local/bin/airport"
+
+  # Do nothing if the file doesn't exist on the platform.
+  [ ! -e "$airport_src" ] && return
+
+  echo -n "Checking for airport shortcut... "
+  if [ ! -e "$airport_dst" ]; then
+    echo -n "not found, linking..."
+    ln -s "$airport_src" "$airport_dst"
+    echo "done"
+  else
+    echo "present"
+  fi
+}
+
+link_airport_cmd
diff --git a/hooks/pre-up/01-rcrc b/hooks/pre-up/01-rcrc
--- a/hooks/pre-up/01-rcrc
+++ b/hooks/pre-up/01-rcrc
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
 function find_defined_tags() {
   local dotfiles_dirs=${DOTFILES_DIRS:="${HOME}/.dotfiles"}
   local tags=()
@@ -12,13 +14,18 @@ function find_defined_tags() {
 }
 
 function write_rcrc() {
+  echo -n "Checking for ~/.rcrc... "
+
   local defined_tags=$(find_defined_tags)
   local rcrc=${RCRC:="${HOME}/.rcrc"}
 
   if [ -e "$rcrc" ]; then
+    echo "present"
     return
   fi
 
+  echo "not found"
+  echo
   echo "It looks like you don't have an .rcrc set up. You can silence this"
   echo "warning with:"
   echo
diff --git a/hooks/pre-up/03-fzf b/hooks/pre-up/03-fzf
--- a/hooks/pre-up/03-fzf
+++ b/hooks/pre-up/03-fzf
@@ -1,19 +1,23 @@
 #!/usr/bin/env bash
 
 # Exit immediately on error
-set -e
-
-LOCAL="${HOME}/.local"
-FZF_HOME="${LOCAL}/lib/fzf"
+set -euo pipefail
 
 install_fzf() {
-  echo "Installing FZF…"
-  git clone --depth 1 https://github.com/junegunn/fzf.git "$FZF_HOME"
-  "${FZF_HOME}/install" --bin
-  ln -s ../lib/fzf/bin/fzf "${LOCAL}/bin/fzf"
-  echo "FZF installed"
+  echo -n "Checking for fzf... "
+
+  local local="${HOME}/.local"
+  local fzf_home="${local}/lib/fzf"
+  if [ -d "$fzf_home" ]; then
+    echo "present"
+    return
+  fi
+
+  echo "not found, installing..."
+  git clone --depth 1 https://github.com/junegunn/fzf.git "$fzf_home"
+  "${fzf_home}/install" --bin
+  ln -s ../lib/fzf/bin/fzf "${local}/bin/fzf"
+  echo "Installed fzf"
 }
 
-if [ ! -d "$FZF_HOME" ]; then
-  install_fzf
-fi
+install_fzf
