nerdherd-review: Open in work Chrome window
I don't know why, but sometimes my terminal gets into a state where
xdg-open doesn't open tabs in the latest Chrome window, but always opens
them in the _first_ chrome window. Fortunately, if I explicitly call
Chrome, I can force a particular profile, causing the links to be opened
in the right window no matter what.

I also wrapped the main logic in a `main` function.

diff --git a/tag-linux-laptop/local/bin/nerdherd-review b/tag-linux-laptop/local/bin/nerdherd-review
--- a/tag-linux-laptop/local/bin/nerdherd-review
+++ b/tag-linux-laptop/local/bin/nerdherd-review
@@ -1,26 +1,41 @@
 #!/usr/bin/env bash
 
-shortopts=hd:p
-longopts=help,closed:,prs
-TEMP=$(getopt -o $shortopts --long $longopts -n gh-issues -- "$@")
-if [ $? != 0 ]; then echo "failed to parse options" >&2; exit 1; fi
+main() {
+  shortopts=hd:p
+  longopts=help,closed:,prs
+  TEMP=$(getopt -o $shortopts --long $longopts -n gh-issues -- "$@")
+  if [ $? != 0 ]; then echo "failed to parse options" >&2; exit 1; fi
 
-closed="1w"
-prs=
+  closed="1w"
+  prs=
 
-eval set -- "$TEMP"
-while true; do
-  case "$1" in
-    -h | --help) print_help; exit; shift ;;
-    -d | --closed) closed="$2"; shift 2 ;;
-    -p  | --prs) prs="--prs"; shift ;;
-    --) shift; break ;;
-    *) echo "error parsing options"; exit 1 ;;
-  esac
-done
+  eval set -- "$TEMP"
+  while true; do
+    case "$1" in
+      -h | --help) print_help; exit; shift ;;
+      -d | --closed) closed="$2"; shift 2 ;;
+      -p  | --prs) prs="--prs"; shift ;;
+      --) shift; break ;;
+      *) echo "error parsing options"; exit 1 ;;
+    esac
+  done
 
-cmd="gh-issues --closed '${closed}' ${prs} --json"
-echo "$cmd"
-ssh com "$cmd" \
-  | jq -r '.[].url' \
-  | xargs -n1 open 2>/dev/null 1>&2
+  cmd="gh-issues --closed '${closed}' ${prs} --json"
+  echo "$cmd"
+  ssh com "$cmd" \
+    | jq -r '.[].url' \
+    | open_in_work_profile
+}
+
+open_in_work_profile() {
+  # ~/.var/app/org.chromium.Chromium/config/chromium/Profile\ 1 corresponds to the profile that I
+  # use for work.
+  while read -r url; do
+    flatpak run org.chromium.Chromium \
+      --profile-directory="Profile 1" \
+      --new-tab "$url" \
+      2>/dev/null 1>&2 &
+  done
+}
+
+main "$@"
